download-external-modules: true
quiet: true
skip-check:
  # Github: Ensure top-level permissions are not set to write-all
  - CKV2_GHA_1

  # Ensure that COPY is used instead of ADD in Dockerfiles
  - CKV_DOCKER_4

  # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_2

  # Ensure that a user for the container has been created
  - CKV_DOCKER_3
