# https://pre-commit.com/
# More hooks available at:
# https://pre-commit.com/hooks.html

# INSTALL ON MAC:
# brew install pre-commit

# INSTALL ON WINDOWS:
# pip install pre-commit

# INSTALL hooks for this workspace
# pre-commit install

exclude: '^modules/external/.*$'

repos:
  # PRECOMMIT - GENERAL
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-case-conflict
      - id: check-json
        exclude: tsconfig.json|devcontainer.json
      # - id: pretty-format-json
      #   exclude: tsconfig.json|package-lock.json|package.json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        exclude: cloud-init-ephemeral.yaml|cloud-init.yaml
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: no-commit-to-branch
        args: ['--branch', 'develop', '--branch', 'main', '--branch', 'master']
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # CODESPELL
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      args: ['--write-changes']

  # SHFMT
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
    # Choose one of:
    - id: shfmt # prebuilt upstream executable

  # SHELLCHECK
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
    - id: shellcheck
      args: ["--severity=warning"]  # Optionally only show errors and warnings

  # TERRAFORM
  # If running tf-docs it must be run first to avoid race condition relating to version constraints.
  # BUG: terraform_docs hook conflicts when used more than once.
  # Workaround with Python
  - repo: local
    hooks:
    - id: Terraform docs
      name: Terraform docs
      entry: python examples/terraform-docs.py
      language: system
      types: [python]
      always_run: true
      pass_filenames: false

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      # - id: terraform_docs
      #  args:
      #    - --args=--lockfile=false
      #    - --args=--config=.tfdocs-config.yml
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
        # [^/]+: Exclude root module. Validation is done via examples/basic
        # see https://github.com/antonbabenko/pre-commit-terraform#terraform_validate
        exclude: |
          (?x)^(
              tests/.*|
              [^/]+|
          )$
      - id: terraform_tflint
        # Configure tflint by creating and updating the config file below.
        args: ["--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"]

  # PYTHON
  # ruff - must be placed before other repos
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
