# https://aquasecurity.github.io/tfsec

# Checks available at:
# https://aquasecurity.github.io/tfsec/v0.61.0/checks/aws/api-gateway/enable-access-logging/

# INSTALL ON MAC:
# brew install tfsec

# INSTALL ON WINDOWS:
# choco install tfsec

# USAGE:
# tfsec --config-file .tfsec.config.yml

---
exclude:
# Add IDs of checks to ignore them
#  - aws-sns-topic-encryption-use-cmk
