[tools]
awscli = 'latest'
black = 'latest'
jq = 'latest'
node = 'latest'
pre-commit = 'latest'
python = '3.10.8'
ruff = 'latest'
shellcheck = 'latest'
starship = 'latest'
terraform = '1.5.7'
terraform-docs = 'latest'
tflint = 'latest'
