#cloud-config
# See https://cloudinit.readthedocs.io/en/latest/

### Helpful commands ##
# sudo cat /var/lib/cloud/instance/user-data.txt
# sudo cat /var/log/cloud-init-output.log
# cloud-init devel schema --config-file x.yaml

# Install additional packages on first boot
package_update: true
package_reboot_if_required: true
packages:
  - awscli
  - jq
  ###########################################
  # Extra packages
%{~ for X in PACKAGES }
  - ${X}
%{~ endfor }
  ###########################################
  ###########################################

runcmd:
  ###########################################
  # Extra runcmds
  - echo ==== EXTRA RUNCMDS ====
%{~ for X in RUNCMDS }
  - ${X}
%{~ endfor }
  ###########################################
  ########################################### 
  - echo ==== ACTIONS-RUNNER ====
  # install actions-runner
  - mkdir actions-runner && cd actions-runner
  - curl -s https://github.com/actions/runner/releases | grep -o -E "https://github.*actions-runner-linux-x64-[0-9\.]+.tar.gz" | sort | uniq > versions.txt
  - RUNNER_FILE_LINK=`cat versions.txt | tail -n1`
  - curl -o actions-runner-linux-x64.tar.gz -L $RUNNER_FILE_LINK
  - tar xzf ./actions-runner-linux-x64.tar.gz
  - cd ..
  - mv actions-runner /home/ubuntu/actions-runner
  - sudo chown -R ubuntu:ubuntu /home/ubuntu

  # configure actions-runner
  - PERSONAL_ACCESS_TOKEN=`aws ssm get-parameter --with-decryption --name ${SSM_PARAMETER_NAME} --region ${SSM_REGION} | jq -r '.Parameter.Value'`
  - >
    TOKEN_RESPONSE=`curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $PERSONAL_ACCESS_TOKEN" https://api.github.com/orgs/${GITHUB_ORGANISATION_NAME}/actions/runners/registration-token`
  - TOKEN=`echo $TOKEN_RESPONSE | jq -r '.token'`
  - su ubuntu -c "/home/ubuntu/actions-runner/config.sh --url '${GITHUB_URL}' --unattended --token $TOKEN ${ARG_NAME} ${ARG_RUNNERGROUP} ${ARG_LABELS}"
  # Install as service
  - cd /home/ubuntu/actions-runner/ && bash ./svc.sh install ubuntu
  - echo ==== ACTIONS-RUNNER DONE ====

power_state:
    mode: reboot

###########################################
# Other
%{~ if length(OTHER) > 0 }
${OTHER}
%{~ endif }
