#cloud-config
# See https://cloudinit.readthedocs.io/en/latest/

# ## Helpful commands ##
# sudo cat /var/lib/cloud/instance/user-data.txt
# sudo cat /var/log/cloud-init-output.log
# cloud-init devel schema --config-file x.yaml

# Install additional packages on first boot
package_update: true
package_reboot_if_required: true
packages:
- awscli
- jq
- parallel
# ##########################################
# Extra packages
%{~ for X in PACKAGES }
- ${X}
%{~ endfor }
# ##########################################
# ##########################################
write_files:
- path: /home/ubuntu/ephemeral_runner.sh
  permissions: '700'
  content: |
    #!/bin/bash
    set -e
    [ "$#" -eq 1 ] || die "1 argument required, $# provided."
    RUN=$1
    cp -R /home/ubuntu/actions-runner /home/ubuntu/actions-runner-$RUN
    PERSONAL_ACCESS_TOKEN=`aws ssm get-parameter --with-decryption --name ${SSM_PARAMETER_NAME} --region ${SSM_REGION} | jq -r '.Parameter.Value'`
    [ "$${#PERSONAL_ACCESS_TOKEN}" -gt 0 ] || die "Unable to retrieve access token."
    TOKEN_RESPONSE=`curl -s -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $PERSONAL_ACCESS_TOKEN" "https://api.github.com/orgs/${GITHUB_ORGANISATION_NAME}/actions/runners/registration-token"`
    TOKEN=`echo $TOKEN_RESPONSE | jq -r '.token')`
    [ "$${#TOKEN}" -ne "null" ] || die "Unable to retrieve token."
    NAME=`hostname`-run-$RUN
    /home/ubuntu/actions-runner-$RUN/config.sh --url '${GITHUB_URL}' --ephemeral --disableupdate --token $TOKEN --name $NAME ${ARG_RUNNERGROUP} ${ARG_LABELS}
    cd /home/ubuntu/actions-runner-$RUN/ && bash ./run.sh
- path: /home/ubuntu/ephemeral_runner_svc.sh
  permissions: '700'
  content: |
    #!/bin/bash
    seq 99999 | parallel -a - 'su ubuntu -c "/home/ubuntu/ephemeral_runner.sh {}" && rm -rf /home/ubuntu/actions-runner-{}'
- path: /etc/systemd/system/this.service
  content: |
    [Unit]
    Description=this service
    After=network.target
    [Service]
    Type=simple
    User=ubuntu
    ExecStart=/home/ubuntu/ephemeral_runner_svc.sh
    [Install]
    WantedBy=multi-user.target
%{~ for X in WRITE_FILES }
- ${X}
%{~ endfor }
runcmd:
# ##########################################
# Extra runcmds
- echo ==== EXTRA RUNCMDS ====
%{~ for X in RUNCMDS }
- ${X}
%{~ endfor }
# ##########################################
# ########################################## 
- echo ==== ACTIONS-RUNNER ====
# download actions-runner
- mkdir actions-runner && cd actions-runner
- curl -s https://github.com/actions/runner/releases | grep -o -E "https://github.*actions-runner-linux-x64-[0-9\.]+.tar.gz" | sort | uniq > versions.txt
- RUNNER_FILE_LINK=`cat versions.txt | tail -n1`
- curl -o actions-runner-linux-x64.tar.gz -L $RUNNER_FILE_LINK
- tar xzf ./actions-runner-linux-x64.tar.gz
- cd ..
- mv actions-runner /home/ubuntu/actions-runner
- chown -R ubuntu:ubuntu /home/ubuntu
- chmod a+r -R /home/ubuntu/actions-runner
- systemctl enable this.service

power_state:
  mode: reboot

# ##########################################
# Other
%{~ if length(OTHER) > 0 }
${OTHER}
%{~ endif }
