name: release

# Overview ref: https://github.com/googleapis/release-please
# Configuration ref: https://github.com/google-github-actions/release-please-action

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  release-please:
    name: 🙏 release-please
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          # These bumps are honoured only if there is an
          # initial tag of v0.1.0 . Create it manually if needed.
          #
          # BREAKING CHANGE only bumps semver minor if version < 1.0.0
          bump-minor-pre-major: true
          # feat commits bump semver patch instead of minor if version < 1.0.0
          bump-patch-for-minor-pre-major: true
          # prerelease when committing to develop
          prerelease: ${{ github.ref == 'refs/heads/develop' }}
      #--------------------------------------------
      # Comment
      #--------------------------------------------
      - name: comment
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request' && steps.release.outputs.releases_created
        with:
          message: |
            :white_check_mark: **Release PR details** :white_check_mark:

            ${{ steps.release.outputs.pr }}

            #${{ steps.release.outputs.pr.number }}
